version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:7
    ports:
      - 27117:27017
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
    networks:
      - backend

networks:
  backend:

volumes:
  mongo-data:
