version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - router01
    networks:
      - backend

## Router
  router01:
    image: mongo:7.0
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017 --bind_ip_all
    ports:
      - 27117:27017
    volumes:
      - ./scripts:/scripts
    networks:
      - backend

## Config Servers
  configsvr01:
    image: mongo:7.0
    container_name: mongo-config-01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts 
    ports:
      - 27119:27017
    links:
      - shard01-a
      - shard02-a 
    networks:
      - backend

## Shards
  ## Shards 01
  shard01-a:
    image: mongo:7.0
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
    ports:
      - 27122:27017
    networks:
      - backend

  ## Shards 02
  shard02-a:
    image: mongo:7.0
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
    ports:
      - 27125:27017
    networks:
      - backend

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - router01
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://router01:27017
    networks:
      - backend

networks:
  backend:
